# FROM ebian::bullseye
# RUN apt update -y &&
#     apt install -y nginx  openssl && \
#     mkdir -p /etc/nginx/ssl \
#     openssl req -x509 -nodes    \
#     -keyout /etc/nginx/ssl/inception.key \
#     -out /etc/nginx/ssl/inception.crt \
#     -subj "/C=FR/ST=BG/L=1337/O=42/0U=42/CN=yregragu.42.ma/UID=yregragu"

# COPY config/nginx.conf /etc/nginx/nginx.conf
# CMD ["nginx", "-g", "daemon off;"]

FROM alpine:latest

RUN apk update && apk add \
    nginx \
    openssl

RUN mkdir -p /etc/nginx/ssl

RUN openssl req -x509 -nodes -days 365 \
    -subj "/C=MA/ST=Casa/L=Casa/O=42/OU=Student/CN=localhost" \
    -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/server.key \
    -out /etc/nginx/ssl/server.crt

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
