FROM alpin::bullseye
RUN apt update -y /
    apt install -y nginx openssl /
    mkdir -p /etc/nginx/ssl /
    openssl req -x509 -nodes    /
    -keyout /etc/nginx/ssl/inception.key /
    -out /etc/nginx/ssl/inception.crt /
    -subj "/C=FR/ST=BG/L=1337/O=42/0U=42/CN=yregragu.42.ma/UID=yregragu"

COPY config/nginx.conf /etc/nginx/nginx.conf
CMD ["nginx", "-g", "daemon off;"]